config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  get '/auth/google_oauth2', as: 'google_login'
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  get '/property/:user_id/:property_id', to: 'properties#show', as: 'property'

  get '/sign_up', to: 'users#new'
  get '/login', to: 'sessions#new'

  post '/user_properties', to: 'user_properties#create'
  delete 'user_properties', to: 'user_properties#destroy'

  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @user = current_user
    @user_properties = UserPropertiesFacade.new(@user.id).user_properties if @user.present?

    if @user.nil?
      redirect_to root_path
      flash[:error] = "You must be logged in to view this page"
    end

    # if params[:user_id] && params[:property_id]
    #   @property = SavedFacade.new(params[:user_id], params[:property_id]).property
    # end

    if params[:search_street] && params[:search_zip]
      @property = SearchFacade.new(params[:search_street], params[:search_zip]).property
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show
    @user = current_user
    @user_properties = UserPropertiesFacade.new(@user.id).user_properties if @user.present?
    @property = SavedFacade.new(params[:user_id], params[:property_id]).property
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth_hash = request.env['omniauth.auth']
    google_id = auth_hash['uid']
    email = auth_hash['info']['email']
    token = auth_hash['credentials']['token']

    user = User.find_or_create_by(email: email)
    user.update(google_id: google_id, token: token)

    session[:user_id] = user.id

    redirect_to '/dashboard'
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  def new; end
end

app/controllers/user_properties_controller.rb
class UserPropertiesController < ApplicationController
  def create
    RentInformService.new.save_property(params[:user_id], params[:property_id])
    redirect_back_or_to dashboard_path
  end

  def destroy
    RentInformService.new.unsave_property(params[:user_id], params[:property_id])
    redirect_back_or_to dashboard_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def prop_ids(user_properties)
    user_properties.map(&:id)
  end

  def map(lat, lon)
    "https://www.mapquestapi.com/staticmap/v5/map?locations=#{lat}, #{lon}&size=1000, 1000&zoom=13&center=#{lat}, #{lon}&defaultMarker=marker-lg-2b6bb0&key=#{ENV['MAPQUEST_KEY']}"
  end

  def format_parks(parks)
    return [{ name: 'No parks found.', street: '' }] if parks.empty?

    [{ name: parks[:park_1_name], street: parks[:park_1_street] },
     { name: parks[:park_2_name], street: parks[:park_2_street] },
     { name: parks[:park_3_name], street: parks[:park_3_street] }]
  end
end

app/views/dashboard/_result_property.html.erb
<div id="property-<%= @property.id %>" class='p-6 border border-gray-300 rounded-lg shadow-md hover:shadow-lg'>
  <div class="flex justify-between">
    <div class="text-xl font-semibold">
      <h1><%= @property.street.titleize %>, Philadelphia, PA <%= @property.zip[0..4] %></h1>
    </div>

    <% if !prop_ids(@user_properties).include?(@property.id)%>
      <%= render partial: 'shared/save_unsave_button', locals: { url: user_properties_path, method: :post, property: @property, button: "Save" } %>
    <% else %>
      <%= render partial: 'shared/save_unsave_button', locals: { url: user_properties_path, method: :delete, property: @property, button: "Unsave" } %>
    <% end %>

  </div>
  
  <p>This property is certified to rent!</p>

  <%= render partial: 'shared/property_button', locals: { url: property_path(@user.id, @property.id), method: :get, property: @property, button: "More Details", style: 'text-blue-600 underline hover:text-blue-900 cursor-pointer' } %>
</div>

app/views/dashboard/_saved_property.html.erb
<div id="property-<%= property.id %>" class='p-6 border border-gray-300 rounded-lg shadow-md hover:shadow-lg'>
  <div class="flex justify-between">
    <div class="text-lg font-semibold">
      <h1><%= property.street.titleize %></h1>
      <h1>Philadelphia, PA <%= property.zip[0..4] %></h1>
    </div>
    <%= render partial: 'shared/save_unsave_button', locals: { url: user_properties_path, method: :delete, property: property, button: "Unsave" } %>
  </div>
  <div>
    <%= render partial: 'shared/property_button', locals: { url: property_path(@user.id, property.id), method: :get, property: property, button: "More Details", style: 'text-blue-600 underline hover:text-blue-900 cursor-pointer' } %>
  </div>
</div>

app/views/dashboard/_search_form.html.erb
<%= form_with url: dashboard_path, method: :get, id: 'search', class: 'flex gap-2' do |f| %>
    <%= f.search_field :search_street, placeholder: '123 Main Street', class: 'border border-gray-300 rounded-md flex-1' %>
    <%= f.search_field 'Philadelphia', value: 'Philadelphia', class: 'border border-gray-300 rounded-md w-1/6' %>
    <%= f.search_field 'PA', value: 'PA', class: 'border border-gray-300 rounded-md w-1/6' %>
    <%= f.search_field :search_zip, placeholder: '12345', class: 'border border-gray-300 rounded-md w-1/5' %>
    <%= f.submit "Search", class: 'inline-block px-4 py-2 text-s font-bold leading-none text-white text-center transition-all duration-200 bg-blue-700 border-2 border-blue-700 shadow-md fold-bold hover:bg-white hover:text-blue-700 rounded' %>
<% end %>

app/views/dashboard/show.html.erb
<div class="flex flex-col gap-12 w-full px-20">
  <div id='welcome' class="text-xl font-semibold mt-12">
    Hey <%= @user.email %>!
  </div>

  <div id="find-property" class='w-full'>
    <div class="text-2xl font-bold mb-4">
      Find a Compliant Property
    </div>
    <div id='search-box' class='flex flex-col w-full gap-4'>
      <%= render partial: 'search_form' %>

      <div id="Result" class=''>
        <% if @property.is_a? SearchError %>
          <div class='p-6 border border-gray-300 rounded-md shadow-md'>
            <p class='font-lg font-semibold text-red-400'>
              Sorry, we can&apos;t find this address in Philadelphia&apos;s Certificate of Rental Suitability database.
            <p>
            <p class='font-sm text-gray-600'>
              For more information about this certification and landlord-tenant rights and responsibilities,
              view the Partners in Good Housing brochure
              <a class='text-blue-500 hover:text-blue-700 underline'
                href='https://www.phila.gov/documents/partners-in-good-housing-brochures/' target="_blank">here</a>.
            </p>
          </div>
        <% elsif @property.is_a? Property %>
            <%= render partial: 'result_property' %>
        <% end %>
      </div>
    </div>    
  </div>

  <div id="Saved">
    <div class="text-2xl font-bold mb-4">
      Saved Properties
    </div>
    <div class=''>
      <% if @user_properties.empty? %>
        <div class='border border-gray-300 rounded-lg w-full p-4'>
          <div class="text-lg font-semibold">
            No properties saved... yet!
          </div>
          <div class="text-sm text-gray-600">
            Search and save a property to view it here
          </div>
        </div>
      <% else %>
        <div class='grid grid-cols-3 gap-4'>
          <% @user_properties.each do |property|%>
              <%= render partial: 'saved_property', locals: { property: property } %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<style>
    @media(max-width:1520px) {
        .left-svg {
            display: none;
        }
    }
  
    /* small css for the mobile nav close */
    #nav-mobile-btn.close span:first-child {
        transform: rotate(45deg);
        top: 4px;
        position: relative;
        background: #a0aec0;
    }
  
    #nav-mobile-btn.close span:nth-child(2) {
        transform: rotate(-45deg);
        margin-top: 0px;
        background: #a0aec0;
    }
  </style>
  
  <header class="fixed top-0 z-50 w-full h-20 bg-white shadow-lg">
    <div class="flex items-center h-full mx-20 justify-between">
      <a href="/" class="relative flex items-center h-full font-black leading-none">
        <%= image_tag 'rent_inform_logo.svg', title: "RentInform Logo", class: "logo h-8" %>
      </a>
      
      <% if current_user %>
        <div id="header-buttons" class="w-64 gap-4 flex items-center">
          <a href="/dashboard"
              class="relative z-40 inline-block w-[132px] h-full py-2 text-sm font-bold leading-none text-center transition-all duration-200 border-2 border-blue-700 rounded shadow-md fold-bold sm:w-full text-blue-700 hover:bg-blue-700 hover:text-white">My Dashboard</a>
          <div class="relative z-40 inline-block w-[132px] h-full py-2 text-sm font-bold leading-none text-white text-center transition-all duration-200 bg-blue-700 border-2 border-blue-700 rounded shadow-md fold-bold sm:w-full hover:bg-white hover:text-blue-700">
            <%= button_to "Log out", logout_path, method: :delete %>
          </div>
        </div>
      <% else %>
        <div id="header-buttons" class="w-64 gap-4 flex items-center">
          <a href="/login"
              class="relative z-40 inline-block w-[132px] h-full py-2 text-sm font-bold leading-none text-center transition-all duration-200 border-2 border-blue-700 rounded shadow-md fold-bold sm:w-full text-blue-700 hover:bg-blue-700 hover:text-white ">Log in</a>
          <a href="/sign_up"
              class="relative z-40 inline-block w-[132px] h-full py-2 text-sm font-bold leading-none text-white text-center transition-all duration-200 bg-blue-700 border-2 border-blue-700 rounded shadow-md fold-bold sm:w-full hover:bg-white hover:text-blue-700">Sign up</a>
        </div>
      <% end %>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RentInform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.9.2/tailwind.min.css">
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: type %>
    <% end %>
    <div class="mt-20">
      <%= yield %>
    </div>
  </body>
</html>

app/views/properties/show.html.erb
<div class='fixed bottom-0 left-0 overflow-y-auto shadow-lg' style="top: 80px; min-width: 550px; max-width: 550px;">
  <%= render partial: 'shared/property_details' %>
</div>

<div class='fixed bottom-0 right-0' style="top: 80px; left: 550px">
  <div id='Map' class="h-full">
    <%= image_tag(map(@property.lat, @property.lon), alt: 'Map', class: "object-cover h-full w-full") %>
  </div>
</div>

app/views/shared/_certified_card.html.erb
<div class='mt-2 shadow-lg border border-gray-200 p-4 rounded-md flex-1 flex items-center gap-4'>
  <img class='w-16 h-16' src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png?20200417132424" alt="Green circle with white checkmark">
  <div>
    <p class="font-semibold text-xl">Certified to Rent</p>
    <p class="text-xs">This property is code-compliant. <a class='text-xs text-blue-700 underline hover:text-blue-900' href='https://www.phila.gov/documents/partners-in-good-housing-brochures/' target="_blank">Learn more</a></p>
    
  </div>
</div>

app/views/shared/_google_button.html.erb
<div id='google-link'>
  <a href=<%= path %> >
    <%= image_tag 'btn_google_signin.png', class: 'w-48 hover:shadow-lg ' %>
  </a>
</div>

<!-- Google Button WIP
<script src="https://accounts.google.com/gsi/client" async></script>
<div id="g_id_onload"
    data-client_id="<%= ENV['GOOGLE_CLIENT_ID'] %>"
    data-login_uri="/auth/google_oauth2">
</div>
<div class="g_id_signin"
    data-type="standard"
    data-size="large"
    data-theme="outline"
    data-text="sign_in_with"
    data-shape="rectangular"
    data-logo_alignment="left">
</div>
-->

app/views/shared/_property_button.html.erb
<%= form_with url: url, method: method, local: true do |f| %>
  <%= f.hidden_field :user_id, value: @user.id%>
  <%= f.hidden_field :property_id, value: property.id%>
  <%= f.submit button, class: style  %>
<% end %>

app/views/shared/_property_details.html.erb
<div id="Result" class='flex flex-col mt-4 px-6 py-4 rounded-md gap-4 bg-white'>
  <div class="flex flex-row justify-between">
    <div class="font-semibold text-2xl">
      <h1><%= @property.street.titleize %>,</h1>
      <h1>Philadelphia, PA <%= @property.zip[0..4] %></h1>
    </div>
    <div id='save-unsave'>
      <% if !prop_ids(@user_properties).include?(@property.id) %>
        <%= render partial: 'shared/save_unsave_button', locals: { url: user_properties_path, method: :post, property: @property, button: "Save" } %>
      <% else %>
        <%= render partial: 'shared/save_unsave_button', locals: { url: user_properties_path, method: :delete, property: @property, button: "Unsave" } %>
      <% end %>
    </div>
  </div>

  <%= render partial: 'shared/certified_card' %>

  <h2 class='text-xl font-semibold leading-none mt-8'>
    Scores
  </h2>
  
  <div class="grid grid-cols-4 justify-between gap-2">
    <%= render partial: 'shared/score_card', locals: { title: "Walk Score", score: @property.walk_score, url_learn_more: 'https://www.walkscore.com/how-it-works/' } %>
    <%= render partial: 'shared/score_card', locals: { title: "Bike Score", score: @property.bike_score, url_learn_more: 'https://www.walkscore.com/how-it-works/' } %>
    <%= render partial: 'shared/score_card', locals: { title: "Transit Score", score: @property.transit_score, url_learn_more: 'https://www.walkscore.com/how-it-works/' } %>
    <%= render partial: 'shared/score_card', locals: { title: "Safety Score", score: (100 - @property.safety_score.to_i), url_learn_more: 'https://geosureglobal.com/' } %>
  </div>

  <div id='Parks' class='w-full'>
    <h2 class="text-xl font-semibold mt-4 mb-4">Nearby Parks</h2>

    <div class='shadow-lg border border-gray-200 rounded-md p-4 flex flex-col gap-4'>
      <% format_parks(@property.parks).each do |park| %>
        <div class="">
          <div class='font-bold text-md text-gray-900'>
            <%= park[:name] %>
          </div>
          <div class='text-sm'>
            <%= park[:street] %>
          </div>
        </div>
      <% end %>
    </div>

    <p class='text-xs mt-4'>
      To find more parks, activities, and green spaces near this address, visit the Parks & Recreation <a class='text-xs text-blue-700 underline hover:text-blue-900' href='https://www.phila.gov/parks-rec-finder/#/locations' target="_blank">Park Finder</a>.
    </p>
  </div>
</div>

app/views/shared/_save_unsave_button.html.erb
<%= form_with url: url, method: method, local: true do |f| %>
  <%= f.hidden_field :user_id, value: @user.id%>
  <%= f.hidden_field :property_id, value: property.id%>
  <label>
    <%= f.submit class: 'hidden' %>
    <% if button == "Save" %>
      <svg class="save w-6 h-6 text-yellow-500 cursor-pointer hover:text-yellow-600" role="button" title="Save" aria-label="Save" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 20">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m13 19-6-5-6 5V2a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v17Z"/>
      </svg>
    <% else %>
      <svg class="unsave w-6 h-6 fill-yellow-500 cursor-pointer" role="button" title="Unsave" aria-label="Unsave" xmlns="http://www.w3.org/2000/svg" fill="#fcc414" viewBox="0 0 14 20">
        <path d="M13 20a1 1 0 0 1-.64-.231L7 15.3l-5.36 4.469A1 1 0 0 1 0 19V2a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v17a1 1 0 0 1-1 1Z"/>
      </svg>
    <% end %>
  </label>
<% end %>

app/views/shared/_score_card.html.erb
    <div class='shadow-md border border-gray-100 p-3 rounded-md flex-1 flex flex-col justify-center items-center gap-4' style="aspect-ratio: 1/1;">
      <p class='text-sm font-bold leading-none'>
        <%= title %>
      </p>
      <div class='w-16 h-16 rounded-full flex justify-center items-center' style='background: radial-gradient(closest-side, white 79%, transparent 80% 100%),
      conic-gradient(<%= score.to_i >= 75 ? 'green' : score.to_i >= 50 ? 'orange' : 'red' %> <%= score %>%, <%= score.to_i >= 75 ? 'lightgreen' : score.to_i >= 50 ? 'bisque' : 'pink' %> 0)' >
        <p class='justify-center'>
          <%= score %>
        </p>
      </div>
      <a class='text-xs text-blue-700 underline hover:text-blue-900' href="<%= url_learn_more %>" target="_blank">Learn more</a>
    </div>

app/views/users/new.html.erb
<div class='mt-28 px-20'>
  <div id='sign-up-box' class='flex border border-gray-300 rounded-lg shadow-lg overflow-hidden'>
  <div id='sign-up-text' class='flex flex-col items-center justify-center w-1/2 gap-6'>
    <div id='title' class='text-4xl font-bold'>
      Find your home
    </div>

    <%= render partial: 'shared/google_button', locals: { path: 'https://accounts.google.com/signup/v2/createaccount?biz=false' } %>

    <div id='login' class='text-sm'>
      Already have an account?
      <a href='/login' class='text-blue-700 underline hover:text-blue-900'>Log in</a>
    </div>
  </div>
  <div id='sign-up-img' class='w-1/2'>
    <img class='w-full h-full object-cover' style='aspect-ratio: 1/1' src="https://images.unsplash.com/photo-1606788075819-9574a6edfab3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=868&q=80">
  </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="flex flex-col gap-32 mt-28 px-20">
  <div id="Main" class="flex justify-between">
    <div id="Description" class="flex flex-col w-1/3 gap-6 justify-center ">
      <div class='flex flex-col gap-3'>
        <div class="text-4xl font-bold leading-tight">
          Find a rental that&apos;s safe and fit for you
        </div>
        <div class="text-md">
          We provide you with code-compliant properties so you can focus on finding the best home for you.
        </div>
      </div>
      <div id="Signup1">
        <a href="/sign_up">
          <div class="relative z-40 inline-block w-40 h-10 px-4 py-3 text-sm font-bold leading-none text-white text-center transition-all duration-300 bg-blue-700 rounded shadow-md fold-bold border-2 border-blue-700 hover:bg-white hover:text-blue-700">
            Sign up
          </div>
        </a>
      </div>
    </div>
    <div id="Image_one" class="w-1/2">
      <img src="https://images.unsplash.com/photo-1559338391-e14b84a22772?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80">
    </div>
  </div>


  <div id="mid_page" class="flex flex-col gap-10 px-16 py-12 border border-solid border-gray-200 rounded-lg shadow-lg">
    <div class="text-3xl font-bold text-center">
      Sometimes pictures aren&apos;t enough
    </div>
    <div id="mid_page_ex" class="flex flex-row justify-between gap-8 font-semibold">
      <div id="mid_page_pic1" class="flex flex-col gap-6">
        <div style="width: 350px; height: 250px" >
          <img class="object-cover w-full h-full" src="https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=874&q=80">
        </div>
        <div class="text-base text-center">
          Up to building code?
        </div>
      </div>
      <div id="mid_page_pic2" class="flex flex-col gap-6">
        <div style="width: 350px; height: 250px">
          <img class="object-cover  w-full h-full" src="https://images.unsplash.com/photo-1597026405082-eda9beae7513?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80">
        </div>
        <div class="text-base text-center">
          Safe neighborhood?
        </div>
      </div>
      <div id="mid_page_pic3" class="flex flex-col gap-6">
        <div style="width: 350px; height: 250px">
          <img class="object-cover  w-full h-full" src="https://images.unsplash.com/photo-1584278140365-2ab8bff2be82?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80">
        </div>
        <div class="text-base text-center">
          Lifestyle fit?
        </div>
      </div>
    </div>
  </div>

  <div id="bottom_page" class="flex flex-row gap-10">
    <div class="w-1/2">
      <img src="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=780&q=80">
    </div>
    <div id="bottom_page-examples" class="flex flex-col w-1/3 gap-8 justify-center">
      <div class='flex flex-col gap-6'>
        <div class='flex gap-2'>
          <div class="text-4xl font-bold text-left pt-2">
            With
          </div>
          <%= image_tag 'rent_inform_logo.svg', alt: "RentInform", class: 'logo', style: "height: 40px; margin-top: 2px" %>
        </div>
        <div id='feature-list' class='flex flex-col gap-4'>
          <div class='flex flex-row gap-4'>
            <img class="w-6 h-6" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png?20200417132424">
            <div class="text-xl">
              City Code Compliance Check
            </div>
          </div>
          <div class='flex flex-row gap-4'>
            <img class="w-6 h-6" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png?20200417132424">
            <div class="text-xl">
              Walk Score
            </div>
          </div>
          <div class='flex flex-row gap-4'>
            <img class="w-6 h-6" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png?20200417132424">
            <div class="text-xl">
              Bike Score
            </div>
          </div>
          <div class='flex flex-row gap-4'>
            <img class="w-6 h-6" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png?20200417132424">
            <div class="text-xl">
              Transit Score
            </div>
          </div>
          <div class='flex flex-row gap-4'>
            <img class="w-6 h-6" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Eo_circle_green_checkmark.svg/512px-Eo_circle_green_checkmark.svg.png?20200417132424">
            <div class="text-xl">
              Safe Place Score
            </div>
          </div>
        </div>
      </div>
      <div id="Signup2">
        <a href="/sign_up">
          <div class="relative z-40 inline-block w-40 h-10 px-4 py-3 text-sm font-bold leading-none text-white text-center transition-all duration-300 bg-blue-700 rounded shadow-md fold-bold border-2 border-blue-700 hover:bg-white hover:text-blue-700">
            Sign up
          </div>
        </a>
      </div>
    </div>
  </div>

  <div id='footer' class="p-20">
  </div>
</div>